### ISSUE TITLE
Issues with `ViewEvent` on Kotlin 1.3.60-eap-25

### ISSUE THREAD

**Issue by ghost** [skoumalcz/teanity#2]
**Describe the bug**
When trying to use ViewEvents with the Kotlin 1.3.60-eap-25 I cannot build. I get the following error:

```
Caused by: java.lang.AssertionError: IR backend shouldn't call KotlinTypeMapper.mapType: OpenNewsEvent
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:261)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapClass(KotlinTypeMapper.kt:222)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:297)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:118)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:137)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:68)
	... 46 more
```

**To Reproduce**
1. Set Kotlin version to 1.3.60-eap-25
2. Try and use `ViewEvent`

**Expected behavior**
No issues.

**Screenshots**
<img width="938" alt="image" src="https://user-images.githubusercontent.com/13090065/67521517-f4943800-f6a2-11e9-8ef8-e19d3edb799a.png">

**Smartphone (please complete the following information):**
N/A

**Additional context**
Latest Teanity `1.0.0-alpha02`

**Comment by ghost** [comment]
After further testing, I have come to the conclusion that this issue only happens when enabling the new Android Jetpack Compose library. It's probably an issue with that.

**Comment by diareuse** [comment]
I think you should leave Teanity out when trying out Compose solely by itself with no backing DataBinding. The Fragments and Activities try to enforce DataBinding, which would in essence prevent you from trying out the Compose since synthetic Views are not implemented yet.

We're keeping an eye on Compose and as soon as it gets into its `alpha` stage, we'll be implementing support for that :) Firstly the 1.0 needs to get stable.

Thanks for reaching out.

**Comment by jan222ik** [comment]
> After further testing, I have come to the conclusion that this issue only happens when enabling the new Android Jetpack Compose library. It's probably an issue with that.

@danteissaias, if you still search for a fix:
I had to add to following in addition to the tutorial on Android Compose [here](https://developer.android.com/jetpack/compose/setup) to compile. (Set compose to false)
```
implementation "androidx.compose:compose-runtime:$compose_version"
    kapt "androidx.compose:compose-compiler:$compose_version"
```
Got this form a tutorial: [here](https://proandroiddev.com/playing-with-jetpack-compose-dev-1-be992c6f8915)

To get a prev in AStudio set compose to true.
